-- =====================================================================
-- DATA GERAKAN INTI — Tahap 2
-- Jalankan SETELAH schema.sql. Aman dijalankan berulang.
-- =====================================================================

insert into public.exercises
 (id, pattern_id, nama, level, alat_dibutuhkan, otot_primer, otot_sekunder,
  cara_melakukan, kesalahan_umum, kenapa_penting, kontraindikasi, sudut_pandang, urutan)
values

('chair-squat','squat',
 '{"id":"Squat ke Kursi","en":"Chair Squat"}','easy','{kursi}',
 '{paha-depan,gluteus}','{paha-belakang,perut-atas}',
 '{"id":["Berdiri membelakangi kursi, kaki selebar bahu","Turun terkontrol 3 hitungan sampai bokong menyentuh kursi","Berat badan di tumit, lutut mengikuti arah ujung kaki","Berdiri kembali tanpa mengayun badan"],
   "en":["Stand with your back to a chair, feet shoulder-width","Lower for a 3-count until you touch the chair","Weight on your heels, knees tracking over your toes","Stand back up without swinging"]}',
 '{"id":"Menjatuhkan badan ke kursi. Justru kontrol turunnya yang melatih otot.","en":"Dropping onto the chair. The controlled descent is what builds strength."}',
 '{"id":"Gerakan dasar berdiri dari duduk — kemampuan paling penting untuk kemandirian sehari-hari.","en":"The fundamental sit-to-stand pattern — the single most important ability for daily independence."}',
 '{}','samping',1),

('sit-to-stand','squat',
 '{"id":"Sit-to-Stand","en":"Sit-to-Stand"}','easy','{kursi}',
 '{paha-depan,gluteus}','{perut-atas}',
 '{"id":["Duduk di tepi kursi, kaki rata di lantai","Condongkan badan sedikit ke depan","Berdiri tanpa bantuan tangan","Duduk kembali perlahan"],
   "en":["Sit at the edge of the chair, feet flat","Lean your torso slightly forward","Stand without using your hands","Sit back down slowly"]}',
 '{"id":"Mendorong dengan tangan. Kalau masih perlu, tidak apa-apa — catat dan kurangi bertahap.","en":"Pushing off with your hands. If you still need to, that is fine — note it and reduce gradually."}',
 '{"id":"Uji fungsi sekaligus latihan. Kemajuannya terasa nyata dalam hidup sehari-hari.","en":"Both a functional test and an exercise. Progress here shows up in real daily life."}',
 '{}','samping',2),

('glute-bridge','hinge',
 '{"id":"Glute Bridge","en":"Glute Bridge"}','easy','{}',
 '{gluteus}','{paha-belakang,erector,perut-bawah}',
 '{"id":["Berbaring telentang, lutut ditekuk, telapak kaki rata di lantai","Tumit didekatkan ke bokong","Kencangkan perut, tekan tumit, angkat panggul","Berhenti saat badan lurus dari lutut ke bahu — jangan lebih tinggi","Tahan 1 detik, turun perlahan 2-3 hitungan"],
   "en":["Lie on your back, knees bent, feet flat","Bring your heels close to your glutes","Brace your core, press through the heels, lift the hips","Stop when your body is straight from knees to shoulders — no higher","Hold 1 second, lower for a 2-3 count"]}',
 '{"id":"Mendorong dengan punggung bawah sampai pinggang melengkung. Kalau pinggang bekerja lebih keras dari bokong, turunkan ketinggiannya.","en":"Pushing from the lower back until it over-arches. If your lower back works harder than your glutes, lift less high."}',
 '{"id":"Penguat bokong paling ramah lutut. Bokong kuat melindungi lutut dan punggung bawah.","en":"The most knee-friendly glute exercise there is. Strong glutes protect the knees and lower back."}',
 '{}','samping',3),

('rdl','hinge',
 '{"id":"Romanian Deadlift","en":"Romanian Deadlift"}','medium','{dumbbell,bar_plate}',
 '{paha-belakang,gluteus}','{erector,trapezius}',
 '{"id":["Berdiri tegak, beban di depan paha","Dorong pinggul ke belakang, lutut hampir tidak menekuk","Beban menyusuri paha sampai terasa tarikan di paha belakang","Kembali berdiri dengan mendorong pinggul ke depan"],
   "en":["Stand tall, weights in front of your thighs","Push your hips back, knees barely bending","Let the weights graze your thighs until you feel a hamstring stretch","Return by driving your hips forward"]}',
 '{"id":"Mengubahnya jadi squat. Lutut hampir tidak bergerak di gerakan ini.","en":"Turning it into a squat. The knees barely move in this movement."}',
 '{"id":"Melatih rantai belakang tubuh — yang paling sering lemah pada orang yang banyak duduk.","en":"Trains the posterior chain — usually the weakest area in people who sit a lot."}',
 '{punggung-bawah}','samping',4),

('floor-press','push_h',
 '{"id":"Floor Press","en":"Floor Press"}','easy','{dumbbell}',
 '{dada,lengan-belakang}','{bahu}',
 '{"id":["Berbaring telentang, lutut ditekuk","Beban di atas dada, siku 45 derajat dari badan","Turunkan sampai lengan atas menyentuh lantai","Jeda sesaat, lalu dorong ke atas"],
   "en":["Lie on your back, knees bent","Weights above your chest, elbows 45 degrees from your body","Lower until your upper arms touch the floor","Pause briefly, then press up"]}',
 '{"id":"Memantulkan siku dari lantai. Harus berhenti dulu, baru dorong.","en":"Bouncing the elbows off the floor. Pause first, then press."}',
 '{"id":"Lantai membatasi jangkauan sehingga bahu aman untuk pemula.","en":"The floor limits the range, keeping the shoulders safe for beginners."}',
 '{bahu}','samping',5),

('wall-pushup','push_h',
 '{"id":"Wall Push-up","en":"Wall Push-up"}','easy','{}',
 '{dada,lengan-belakang}','{bahu,perut-atas}',
 '{"id":["Berdiri menghadap dinding, tangan setinggi bahu","Mundur sampai badan miring","Turunkan dada ke dinding dengan siku menyusuri badan","Dorong kembali"],
   "en":["Face a wall, hands at shoulder height","Step back until your body is angled","Lower your chest to the wall, elbows tucked","Push back"]}',
 '{"id":"Pinggul turun duluan. Badan harus tetap satu garis lurus.","en":"Hips sagging first. Keep your body in one straight line."}',
 '{"id":"Titik masuk paling aman ke pola dorong. Makin mundur, makin berat.","en":"The safest entry into the push pattern. The further back you step, the harder it gets."}',
 '{}','samping',6),

('db-row','pull_h',
 '{"id":"Dumbbell Row","en":"Dumbbell Row"}','easy','{dumbbell}',
 '{punggung-tengah,trapezius,punggung-atas}','{lengan-depan,bahu-belakang,erector}',
 '{"id":["Badan condong 45 derajat, punggung lurus seperti papan","Beban menggantung lurus ke bawah","Tarik beban ke arah pinggang bawah, siku menyusuri badan","Turunkan terkontrol"],
   "en":["Hinge to about 45 degrees, back flat like a plank","Let the weights hang straight down","Pull toward your lower waist, elbows tucked","Lower under control"]}',
 '{"id":"Punggung membulat dan bahu naik ke telinga. Turunkan beban kalau itu terjadi.","en":"Rounding the back and shrugging. Reduce the weight if that happens."}',
 '{"id":"Gerakan terpenting untuk memperbaiki postur orang yang banyak duduk.","en":"The most important movement for fixing posture in people who sit a lot."}',
 '{punggung-bawah}','samping',7),

('band-row','pull_h',
 '{"id":"Band Row Duduk","en":"Seated Band Row"}','easy','{band}',
 '{punggung-tengah,punggung-atas}','{lengan-depan}',
 '{"id":["Duduk di lantai, kaki lurus, band melingkar di telapak kaki","Punggung tegak, tarik band ke arah perut","Remas tulang belikat di akhir tarikan","Lepas perlahan"],
   "en":["Sit on the floor, legs straight, band around your feet","Back tall, pull the band toward your belly","Squeeze the shoulder blades at the end","Release slowly"]}',
 '{"id":"Membungkuk saat menarik. Dada tetap terbuka.","en":"Slouching as you pull. Keep the chest open."}',
 '{"id":"Alternatif row tanpa beban, cocok saat lutut atau punggung sedang tidak nyaman.","en":"A rowing option with no weights, useful when knees or back feel off."}',
 '{}','samping',8),

('shoulder-press','push_v',
 '{"id":"Shoulder Press","en":"Shoulder Press"}','medium','{dumbbell}',
 '{bahu,lengan-belakang}','{trapezius,perut-atas}',
 '{"id":["Berdiri tegak, perut dikencangkan","Beban setinggi bahu","Dorong lurus ke atas tanpa melengkungkan punggung","Turunkan terkontrol ke bahu"],
   "en":["Stand tall, brace your core","Weights at shoulder height","Press straight overhead without arching your back","Lower under control"]}',
 '{"id":"Punggung melengkung ke belakang — tandanya beban terlalu berat.","en":"Arching the back — a sign the weight is too heavy."}',
 '{"id":"Beban paling ringan di sini, dan itu disengaja. Bahu paling mudah cedera.","en":"The lightest load belongs here, deliberately. Shoulders are the easiest joint to hurt."}',
 '{bahu}','samping',9),

('biceps-curl','arms',
 '{"id":"Biceps Curl","en":"Biceps Curl"}','easy','{dumbbell}',
 '{lengan-depan}','{}',
 '{"id":["Berdiri tegak, siku menempel di sisi badan","Angkat beban perlahan tanpa menggerakkan siku","Turunkan lebih perlahan lagi"],
   "en":["Stand tall, elbows pinned to your sides","Curl up slowly without moving the elbows","Lower even more slowly"]}',
 '{"id":"Mengayun badan untuk membantu. Kalau perlu mengayun, beban terlalu berat.","en":"Swinging the body to help. If you need to swing, the weight is too heavy."}',
 '{"id":"Kontribusinya paling kecil terhadap hasil — selalu taruh di akhir sesi.","en":"Contributes least to results — always put it at the end of a session."}',
 '{}','samping',10),

('triceps-dip','arms',
 '{"id":"Trisep Dip Kursi","en":"Chair Triceps Dip"}','medium','{kursi}',
 '{lengan-belakang}','{dada,bahu}',
 '{"id":["Duduk di tepi kursi, tangan di sisi pinggul","Geser bokong keluar dari kursi","Turunkan badan dengan menekuk siku ke belakang","Dorong kembali naik"],
   "en":["Sit at the edge of a chair, hands beside your hips","Slide your hips off the seat","Lower by bending the elbows backwards","Press back up"]}',
 '{"id":"Turun terlalu dalam sampai bahu tertarik ke depan. Berhenti di siku 90 derajat.","en":"Dipping so deep the shoulders roll forward. Stop at 90 degrees."}',
 '{"id":"Melatih lengan belakang tanpa alat apa pun.","en":"Trains the back of the arms with no equipment at all."}',
 '{bahu}','samping',11),

('dead-bug','core',
 '{"id":"Dead Bug","en":"Dead Bug"}','easy','{}',
 '{perut-bawah,perut-atas}','{obliq,erector}',
 '{"id":["Telentang, lengan lurus ke atas, lutut ditekuk 90 derajat","Punggung bawah menempel lantai sepanjang gerakan","Turunkan lengan kanan dan kaki kiri bersamaan","Kembali, lalu ganti sisi"],
   "en":["Lie on your back, arms up, knees bent 90 degrees","Keep your lower back pressed to the floor throughout","Lower the right arm and left leg together","Return, then switch sides"]}',
 '{"id":"Pinggang terangkat dari lantai. Kalau terjadi, kurangi jangkauan kaki.","en":"The lower back lifting off the floor. If it does, reduce how far the leg travels."}',
 '{"id":"Melatih inti tubuh tanpa menekan tulang belakang seperti sit-up.","en":"Trains the core without loading the spine the way sit-ups do."}',
 '{}','samping',12),

('plank','core',
 '{"id":"Plank","en":"Plank"}','medium','{}',
 '{perut-atas,obliq}','{bahu,erector}',
 '{"id":["Tumpu siku dan ujung kaki","Badan lurus dari kepala ke tumit","Kencangkan perut dan bokong","Tahan sesuai waktu, jangan tahan napas"],
   "en":["Support on elbows and toes","Body straight from head to heels","Brace your abs and glutes","Hold for time — keep breathing"]}',
 '{"id":"Pinggul turun atau naik terlalu tinggi. Lebih baik 15 detik lurus daripada 60 detik melengkung.","en":"Hips sagging or piking up. 15 seconds straight beats 60 seconds bent."}',
 '{"id":"Melatih inti tubuh menahan posisi — yang justru paling terpakai sehari-hari.","en":"Trains the core to resist movement — which is what it actually does all day."}',
 '{punggung-bawah}','samping',13),

('bird-dog','core',
 '{"id":"Bird Dog","en":"Bird Dog"}','easy','{}',
 '{erector,perut-atas}','{gluteus,obliq}',
 '{"id":["Posisi merangkak, tangan di bawah bahu, lutut di bawah pinggul","Julurkan lengan kanan dan kaki kiri sampai lurus","Panggul tetap rata, jangan miring","Tahan 2 detik, kembali, ganti sisi"],
   "en":["On all fours, hands under shoulders, knees under hips","Extend the right arm and left leg until straight","Keep the pelvis level, do not tilt","Hold 2 seconds, return, switch sides"]}',
 '{"id":"Mengangkat kaki terlalu tinggi sampai punggung melengkung.","en":"Lifting the leg so high the back arches."}',
 '{"id":"Melatih keseimbangan dan punggung bawah sekaligus — sangat berguna untuk usia lanjut.","en":"Trains balance and the lower back at once — especially valuable for older adults."}',
 '{}','samping',14)

on conflict (id) do update set
  nama = excluded.nama,
  cara_melakukan = excluded.cara_melakukan,
  kesalahan_umum = excluded.kesalahan_umum,
  kenapa_penting = excluded.kenapa_penting,
  otot_primer = excluded.otot_primer,
  otot_sekunder = excluded.otot_sekunder;
